Repository informalsystems/apalache, pull requests merged in 2022-08, with the labels that each got.

#2035 Link to changelog format in PR template
  .github/pull_request_template.md
Labels: DevOps

#2057 Update of set filter rule with SMT arrays
  tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/SetFilterRule.scala
Labels: Farrays

#2084 improve the warning about large sets
  tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/analyses/ExpansionMarker.scala
  tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/SetExpandRule.scala
Labels: usability

#2112 Fix cell type in DomainRuleWithArrays
  tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/DomainRule.scala
  tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/DomainRuleWithArrays.scala
Labels: Farrays
